#!/usr/bin/perl

use HTTP::Tiny;
use JSON;
use Data::Dumper;
use strict;

my $BRIDGE_IP = ""; # put the IP of your Hue bridge here
my $API_KEY = ""; # put your Hue API key here

$| = 1;

while(1) {
	my $r = HTTP::Tiny->new->get("http://$BRIDGE_IP/api/$API_KEY/lights"); 

	my $lights = decode_json $r->{content};
	my $timestamp = time();
	foreach my $id (sort {$lights->{$a}->{'id'} cmp $lights->{$b}->{'id'}} keys %$lights) {
		print join ",", (
			$timestamp,
			$id,
			$lights->{$id}->{'name'},
			$lights->{$id}->{'type'},
			$lights->{$id}->{'state'}->{'on'},
			$lights->{$id}->{'state'}->{'reachable'},
			$lights->{$id}->{'state'}->{'ct'},
			xy_convert($lights->{$id}->{'state'}->{'xy'}),
			$lights->{$id}->{'state'}->{'hue'},
			$lights->{$id}->{'state'}->{'sat'},
			$lights->{$id}->{'state'}->{'bri'},
			$lights->{$id}->{'modelid'},
			$lights->{$id}->{'swversion'},
		);
		print "\n";
	}

	sleep 60;
}

sub xy_convert {
        my $xy = shift;

        if (ref($xy) eq 'ARRAY') {
                return "[$xy->[0],$xy->[1]]";
        } else {
                return "";
        }
}
